version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_ENV: development

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web