"""Inicio Bd

Revision ID: 076a0af6b761
Revises: 
Create Date: 2025-01-10 16:30:25.176771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076a0af6b761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herramienta',
    sa.Column('id_herramienta', sa.Integer(), nullable=False),
    sa.Column('nombre_herramienta', sa.String(length=100), nullable=False),
    sa.Column('descripcion_herramienta', sa.Text(), nullable=True),
    sa.Column('costo_alquiler_dia', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_herramienta')
    )
    op.create_table('mano_de_obra',
    sa.Column('id_mano_de_obra', sa.Integer(), nullable=False),
    sa.Column('nombre_mano_de_obra', sa.String(length=100), nullable=False),
    sa.Column('descripcion_mano_de_obra', sa.Text(), nullable=True),
    sa.Column('costo_hora', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_mano_de_obra')
    )
    op.create_table('material',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('nombre_material', sa.String(length=100), nullable=False),
    sa.Column('descripcion_material', sa.Text(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_table('obra',
    sa.Column('id_obra', sa.Integer(), nullable=False),
    sa.Column('nombre_obra', sa.String(length=100), nullable=False),
    sa.Column('descripcion_obra', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_obra')
    )
    op.create_table('partida',
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('nombre_partida', sa.String(length=100), nullable=False),
    sa.Column('descripcion_partida', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_partida')
    )
    op.create_table(' partidas_materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], name='fk_partidas_materiales_material'),
    sa.ForeignKeyConstraint(['id_partida'], ['partida.id_partida'], name='fk_partidas_materiales_partida'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obras_partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('id_obra', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_obra'], ['obra.id_obra'], name='fk_obras_partidas_obra'),
    sa.ForeignKeyConstraint(['id_partida'], ['partida.id_partida'], name='fk_obras_partidas_partida'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidas_herramientas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('id_herramienta', sa.Integer(), nullable=False),
    sa.Column('cantidad_dias', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_herramienta'], ['herramienta.id_herramienta'], name='fk_partidas_herramientas_herramienta'),
    sa.ForeignKeyConstraint(['id_partida'], ['partida.id_partida'], name='fk_partidas_herramientas_partida'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidas_mano_de_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('id_mano_de_obra', sa.Integer(), nullable=False),
    sa.Column('cantidad_horas', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_mano_de_obra'], ['mano_de_obra.id_mano_de_obra'], name='fk_partidas_mano_de_obra_mano_de_obra'),
    sa.ForeignKeyConstraint(['id_partida'], ['partida.id_partida'], name='fk_partidas_mano_de_obra_partida'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partidas_mano_de_obra')
    op.drop_table('partidas_herramientas')
    op.drop_table('obras_partidas')
    op.drop_table(' partidas_materiales')
    op.drop_table('partida')
    op.drop_table('obra')
    op.drop_table('material')
    op.drop_table('mano_de_obra')
    op.drop_table('herramienta')
    # ### end Alembic commands ###
