"""Relaciones Materiales - Unidad de Medida y Partidas - Unidad de Medidas

Revision ID: 1a93fbbdb372
Revises: 852df0f18ca5
Create Date: 2025-01-13 16:31:59.506037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a93fbbdb372'
down_revision = '852df0f18ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidas_materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], name='fk_partidas_materiales_material'),
    sa.ForeignKeyConstraint(['id_partida'], ['partida.id_partida'], name='fk_partidas_materiales_partida'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(' partidas_materiales')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_unidad_medida', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_registro', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_partida_unidad_medida', 'unidad_medida', ['id_unidad_medida'], ['id_unidad_medida'])
        batch_op.drop_column('unidad_medida')

    with op.batch_alter_table('obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('gastos_administrativos', sa.Date(), nullable=True))

    with op.batch_alter_table('partida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_unidad_medida', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rendimiento', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_partida_unidad_medida', 'unidad_medida', ['id_unidad_medida'], ['id_unidad_medida'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partida', schema=None) as batch_op:
        batch_op.drop_constraint('fk_partida_unidad_medida', type_='foreignkey')
        batch_op.drop_column('rendimiento')
        batch_op.drop_column('id_unidad_medida')

    with op.batch_alter_table('obra', schema=None) as batch_op:
        batch_op.drop_column('gastos_administrativos')
        batch_op.drop_column('cliente_nombre')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_partida_unidad_medida', type_='foreignkey')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('id_unidad_medida')

    op.create_table(' partidas_materiales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_partida', sa.INTEGER(), nullable=False),
    sa.Column('id_material', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], name='fk_partidas_materiales_material'),
    sa.ForeignKeyConstraint(['id_partida'], ['partida.id_partida'], name='fk_partidas_materiales_partida'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('partidas_materiales')
    # ### end Alembic commands ###
