"""Relaciones Materiales - Unidad de Medida y Partidas - Unidad de Medidas

Revision ID: 4363f07a3bba
Revises: e157958540fc
Create Date: 2025-01-13 16:23:14.164342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4363f07a3bba'
down_revision = 'e157958540fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidad_medida',
    sa.Column('id_unidad_medida', sa.Integer(), nullable=False),
    sa.Column('nombre_unidad_medida', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_unidad_medida')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_unidad_medida', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_registro', sa.Date(), nullable=True))
        batch_op.create_foreign_key(None, 'unidad_medida', ['id_unidad_medida'], ['id_unidad_medida'])
        batch_op.drop_column('unidad_medida')

    with op.batch_alter_table('obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('gastos_administrativos', sa.Date(), nullable=True))

    with op.batch_alter_table('partida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_unidad_medida', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rendimiento', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'unidad_medida', ['id_unidad_medida'], ['id_unidad_medida'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partida', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rendimiento')
        batch_op.drop_column('id_unidad_medida')

    with op.batch_alter_table('obra', schema=None) as batch_op:
        batch_op.drop_column('gastos_administrativos')
        batch_op.drop_column('cliente_nombre')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('id_unidad_medida')

    op.drop_table('unidad_medida')
    # ### end Alembic commands ###
