"""Relaciones Materiales - Unidad de Medida y Partidas - Unidad de Medidas

Revision ID: 66037e136611
Revises: bad48b582cb9
Create Date: 2025-01-13 16:35:41.450388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66037e136611'
down_revision = 'bad48b582cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_material')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_unidad_medida', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_registro', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_partida_unidad_medida', 'unidad_medida', ['id_unidad_medida'], ['id_unidad_medida'])
        batch_op.drop_column('unidad_medida')

    with op.batch_alter_table('obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_nombre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gastos_administrativos', sa.Date(), nullable=True))

    with op.batch_alter_table('partida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_unidad_medida', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rendimiento', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_partida_unidad_medida', 'unidad_medida', ['id_unidad_medida'], ['id_unidad_medida'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partida', schema=None) as batch_op:
        batch_op.drop_constraint('fk_partida_unidad_medida', type_='foreignkey')
        batch_op.drop_column('rendimiento')
        batch_op.drop_column('id_unidad_medida')

    with op.batch_alter_table('obra', schema=None) as batch_op:
        batch_op.drop_column('gastos_administrativos')
        batch_op.drop_column('cliente_nombre')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_partida_unidad_medida', type_='foreignkey')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('id_unidad_medida')

    op.create_table('_alembic_tmp_material',
    sa.Column('id_material', sa.INTEGER(), nullable=False),
    sa.Column('nombre_material', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion_material', sa.TEXT(), nullable=True),
    sa.Column('precio_unitario', sa.FLOAT(), nullable=True),
    sa.Column('id_unidad_medida', sa.INTEGER(), nullable=False),
    sa.Column('fecha_registro', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_unidad_medida'], ['unidad_medida.id_unidad_medida'], name='fk_partida_unidad_medida'),
    sa.PrimaryKeyConstraint('id_material')
    )
    # ### end Alembic commands ###
