"""Cambio cantidad en mano de obra y herramientas

Revision ID: b0c59985116f
Revises: 25c808656637
Create Date: 2025-01-15 21:16:56.101858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c59985116f'
down_revision = '25c808656637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidas_herramientas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Float(), nullable=True))
        batch_op.drop_column('cantidad_dias')

    with op.batch_alter_table('partidas_mano_de_obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Float(), nullable=True))
        batch_op.drop_column('cantidad_horas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidas_mano_de_obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_horas', sa.FLOAT(), nullable=True))
        batch_op.drop_column('cantidad')

    with op.batch_alter_table('partidas_herramientas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_dias', sa.FLOAT(), nullable=True))
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
