"""Corrección Nombre Tabla partida-materiales

Revision ID: e157958540fc
Revises: 076a0af6b761
Create Date: 2025-01-13 11:57:49.654666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e157958540fc'
down_revision = '076a0af6b761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidas_materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], name='fk_partidas_materiales_material'),
    sa.ForeignKeyConstraint(['id_partida'], ['partida.id_partida'], name='fk_partidas_materiales_partida'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(' partidas_materiales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(' partidas_materiales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_partida', sa.INTEGER(), nullable=False),
    sa.Column('id_material', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], name='fk_partidas_materiales_material'),
    sa.ForeignKeyConstraint(['id_partida'], ['partida.id_partida'], name='fk_partidas_materiales_partida'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('partidas_materiales')
    # ### end Alembic commands ###
